// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXLM_h3FGTnNMCArz8WhMaDDKeSF_jsE8',
    appId: '1:378811361561:android:ab4352ba1985dfc12e7d88',
    messagingSenderId: '378811361561',
    projectId: 'betcontrol-7d562',
    storageBucket: 'betcontrol-7d562.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcqIAJvaWrklLL_SDkUUVUltj1-9yEFds',
    appId: '1:378811361561:ios:b97dddce54ceb9c62e7d88',
    messagingSenderId: '378811361561',
    projectId: 'betcontrol-7d562',
    storageBucket: 'betcontrol-7d562.firebasestorage.app',
    androidClientId: '378811361561-52prg2o3jf9j45dj9gucsmg0a9ec2hf8.apps.googleusercontent.com',
    iosClientId: '378811361561-s3i28bjbodvd8a54712pf5uuosm72k45.apps.googleusercontent.com',
    iosBundleId: 'com.project.betcontrolMain.DNSFilterExtension',
  );
}
